language: python
python:
  - "3.5"
# command to install dependencies
before_script:

  - FROM debian:latest
  - EXPOSE 5000
  - RUN apt-get update -y
  - RUN apt-get install -yq build-essential python3-pip rsync
  - RUN apt-get install -yq nginx
  - RUN apt-get install -yq python3-venv

  - ADD . /flask-backend
  - WORKDIR /flask-backend

  - ENV VIRTUAL_ENV=/venv
  - RUN python3 -m venv $VIRTUAL_ENV
  - ENV PATH="$VIRTUAL_ENV/bin:$PATH"

  - easy_install distribute
  - RUN pip3 install -r requirements.txt

  - CMD ["gunicorn", "main:app"]
# command to run tests
script:
  - pytest

services:
  - docker
