language: python
python:
- '3.5'
before_script:
- easy_install distribute
- pip3 install -r requirements.txt

# script:
# - pytest

sudo: required

services:
  - docker

before_install:
- cd backend
- docker build -t deep-stock-backend:latest .
- docker run -d -p 5000:5000 deep-stock-backend:latest
- cd ..
- openssl aes-256-cbc -K $encrypted_e7fa7f710305_key -iv $encrypted_e7fa7f710305_iv
  -in deep-stock-268818-fce7b0e95509.json.enc -out deep-stock-268818-fce7b0e95509.json
  -d

deploy:
  provider: gae
  keyfile: "deep-stock-268818-fce7b0e95509.json"
  project: "deep-stock-268818"
  on:
     all_branches: true
