language: python
python:
- '3.5'

before_install:
  - openssl aes-256-cbc -K $encrypted_e7fa7f710305_key -iv $encrypted_e7fa7f710305_iv
    -in deep-stock-268818-fce7b0e95509.json.enc -out deep-stock-268818-fce7b0e95509.json
    -d

# script:
# - pytest

sudo: required

services:
  - dockers

script:
  - docker-compose up --build -d
  #- docker-compose up --build -d
  # - openssl aes-256-cbc -K $encrypted_e7fa7f710305_key -iv $encrypted_e7fa7f710305_iv
  #   -in deep-stock-268818-fce7b0e95509.json.enc -out deep-stock-268818-fce7b0e95509.json
  #   -d

# - cd backend
# - docker build . -t deep-stock-backend:latest
# - docker run -e IV=$encrypted_e7fa7f710305_iv -e KEY=$encrypted_e7fa7f710305_key  -d -p 5000:5000 deep-stock-backend:latest
# - cd ..


before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi


deploy:
  - provider: script
    script: chmod +x gcloud/deploy-prod.sh && gcloud/deploy-prod.sh
    skip_cleanup: true
  # provider: gae
  # keyfile: "deep-stock-268818-fce7b0e95509.json"
  # project: "deep-stock-268818"
    verbosity: debug
    on:
       all_branches: true


# CMD openssl aes-256-cbc -K $KEY -iv $IV \
# -in deep-stock-268818-fce7b0e95509.json.enc -out deep-stock-268818-fce7b0e95509.json \
# -d && gcloud auth activate-service-account travis-key@deep-stock-268818.iam.gserviceaccount.com \
# --key-file deep-stock-268818-fce7b0e95509.json \
# && gcloud app deploy --version Natnael_backend --project deep-stock-268818 --no-promote
