language: python
python:
- '3.5'
# before_script:
# - easy_install distribute
# - pip3 install -r requirements.txt

# script:
# - pytest

sudo: required

services:
  - docker

script:
- cd backend
- ls
- docker build . -t deep-stock-backend:latest
- docker run -e IV=$encrypted_e7fa7f710305_iv -e KEY=$encrypted_e7fa7f710305_key  -d -p 5000:5000 deep-stock-backend:latest
- cd ..

# - openssl aes-256-cbc -K $encrypted_e7fa7f710305_key -iv $encrypted_e7fa7f710305_iv
#   -in deep-stock-268818-fce7b0e95509.json.enc -out deep-stock-268818-fce7b0e95509.json
#   -d
#
# deploy:
#   provider: gae
#   keyfile: "deep-stock-268818-fce7b0e95509.json"
#   project: "deep-stock-268818"
#   default: true
#   on:
#      all_branches: true
